apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-platforms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformservice-d
  template:
    metadata:
      labels:
        app: platformservice-d
    spec:
      containers:
      - name: platformservice-d
        image: ahsansoftengineer/platformservice-d
        ports:
        - containerPort: 5401
        env:
        - name: DOTNET_ENVIRONMENT
          value: "DockerK8S"
        - name: ASPNETCORE_URLS
          value: "http://+:8301"

# CLUSTER IP CONFIG
--- 
apiVersion: v1
kind: Service
metadata:
  name: srv-clusterip-platforms
spec:
  type: ClusterIP
  selector:
    app: platformservice-d
  ports:
  - name: platformservice
    protocol: TCP
    port: 5401
    targetPort: 5401