version: "3.9"

services:
  platformservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: ahsansoftengineer/platformservice-b
    container_name: platformservice-b
    environment:
      - ASPNETCORE_URLS=http://+:5201
      - DOTNET_ENVIRONMENT=DockerCompose
    ports:
      - "5201:5201" # Map host port 5201 to container port 5201