version: "3.9"

services:
  platformservice-b:
    build:
      context: .
      dockerfile: Dockerfile
    image: ahsansoftengineer/platformservice-b
    container_name: platformservice-b
    environment:
      - ASPNETCORE_URLS=http://+:5201
      - DOTNET_ENVIRONMENT=DockerCompose
      - ConnectionStrings__SbPlatform=Server=127.0.0.1,1430;Initial Catalog=PlatformDB;User ID=sa;Password=P@55w0rd!123;TrustServerCertificate=true;
      - CommandService=http://host.docker.internal:8201/api/c/platforms/

    ports:
      - "5201:5201" # Map host port 5201 to container port 5201

## Docker Compose CLI
# docker-compose up -d --build 
# docker-compose down

## ROUTE (Docker Port Mapping)
# - http://localhost:5201/swagger/index.html
# - http://localhost:5201/api/platform
# - http://localhost:5201/api/platform/1

## InterService Comm (Docker Host IP Name)
# - http://host.docker.internal:8201/api/c/platforms/