version: "3.9"

services:
  platformservice-b:
    build:
      context: .
      dockerfile: Dockerfile
    image: ahsansoftengineer/platformservice-b
    container_name: platformservice-b
    environment:
      - ASPNETCORE_URLS=http://+:5201
      - DOTNET_ENVIRONMENT=DockerCompose
      # - ConnectionStrings__PlatformConn=Server=127.0.0.1,1430;Initial Catalog=platformsdb;User ID=sa;Password=P@55w0rd!123;TrustServerCertificate=true;
      # - CommandService=http://host.docker.internal:8201/api/c/platforms/

    ports:
      - "5201:5201" # Map host port 5201 to container port 5201