version: '3.9'

services:
  ms-sql-e:
    image: ahsansoftengineer/ms-sql-e
    container_name: ms-sql-e
    build:
        context: .
        dockerfile: DockerfileSQL
    # environment:
    #   - ACCEPT_EULA=Y
    #   - MSSQL_PID=Express
    #   - SA_PASSWORD=P@55w0rd!123
    volumes:
      - sql-data:/var/opt/mssql
    ports:
      - "1435:1433"
    networks:
      - network-501

  commandsservice-e:
    image: ahsansoftengineer/commandservice-e
    container_name: commandservice-e
    build:
      context: ./../CommandsService/
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8501
      - DOTNET_ENVIRONMENT=Docker501
    ports:
      - "8501:8501"
    networks:
      - network-501

  platformservice-e:
    image: ahsansoftengineer/platformservice-e
    container_name: platformservice-e
    build:
      context: ./../PlatformService/
      dockerfile: Dockerfile-Reference
    # depends_on:
    #   docker-sql-e:
    environment:
      - ConnectionStrings__PlatformConn=Server=ms-sql-e,1433;Database=PlatformDB;User=sa;Password=P@55w0rd!123;TrustServerCertificate=true;
      - ASPNETCORE_URLS=http://+:5501
      - DOTNET_ENVIRONMENT=Docker501
      - CommandService=http://commandsservice-e:8501/api/c/platforms/
    ports:
      - "5501:5501"
    networks:
      - network-501

networks:
  network-501:
    driver: bridge

volumes:
  sql-data:
    driver: local

# docker-compose -f 501-docker-compose.yaml up -d --build
# docker exec -it id sh
# printenv DOTNET_ENVIRONMENT