apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-mssql-sba-hierarchy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-sba-hierarchy
  template:
    metadata:
      labels:
        app: mssql-sba-hierarchy
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          resources:
            limits:
              memory: 1Gi
              cpu: "1"
            requests:
              memory: 1Gi
              cpu: "1"
          env:
            - name: MSSQL_PID
              value: "Express"
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql
                  key: SA_PASSWORD
          volumeMounts:
            - mountPath: /var/opt/mssql/data
              name: mssqldb
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: claim-mssql-sba-hierarchy

---
apiVersion: v1
kind: Service
metadata:
  name: srvc-clusterip-mssql-sba-hierarchy
spec:
  type: ClusterIP
  selector:
    app: mssql-sba-hierarchy
  ports:
    - name: mssql
      protocol: TCP
      port: 1433
      targetPort: 1433

---
apiVersion: v1
kind: Service
metadata:
  name: srvc-loadbalancer-mssql-sba-hierarchy
spec:
  type: LoadBalancer
  selector:
    app: mssql-sba-hierarchy
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
## BASH
# kubectl apply -f ./__K8S/B_DEPL_SQL/depl-mssql-sba-hierarchy.yaml
# kubectl delete -f ./__K8S/B_DEPL_SQL/depl-mssql-sba-hierarchy.yaml

