apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-mssql-sba-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-sba-auth
  template:
    metadata:
      labels:
        app: mssql-sba-auth
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
        # - name: mssql-sba-auth
        #   image: ahsansoftengineer/mssql-sba-auth
          ports:
            - containerPort: 1433
          resources:
            limits:
              memory: 2Gi
              cpu: "2"
            requests:
              memory: 2Gi
              cpu: "2"
          env:
            - name: MSSQL_PID
              value: "Express"
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql
                  key: SA_PASSWORD
            # The commented-out line should be removed if you're using the secret reference
            # - name: SA_PASSWORD
            #   value: "P@55w0rd!123"
          volumeMounts:
            - mountPath: /var/opt/mssql/data
              name: mssqldb
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: claim-mssql-sba-auth

---
# CLUSTER IP FOR MS SQL SERVICE (INTERNAL ACCESS)
apiVersion: v1
kind: Service
metadata:
  name: srvc-clusterip-mssql-sba-auth
spec:
  type: ClusterIP
  selector:
    app: mssql-sba-auth
  ports:
    - name: mssql
      protocol: TCP
      port: 1433
      targetPort: 1433

---
# LOAD BALANCER FOR MS SQL SERVICE (OPTIONAL EXTERNAL ACCESS)
apiVersion: v1
kind: Service
metadata:
  name: srvc-loadbalancer-mssql-sba-auth
spec:
  type: LoadBalancer
  selector:
    app: mssql-sba-auth
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433

## SECRET
# - Becareful with Password Complexity
# kubectl create secret generic mssql --from-literal=SA_PASSWORD='P@55w0rd!123' 
# kubectl describe secret mssql
# kubectl get secret mssql
# kubectl delete secret mssql

## BASH
# kubectl apply -f ./__K8S/B_DEPL_SQL/depl-mssql-sba-auth.yaml
# kubectl delete -f ./__K8S/B_DEPL_SQL/depl-mssql-sba-auth.yaml

# deployment.apps/depl-mssql-sba-auth created
# service/srvc-clusterip-mssql-sba-auth created
# service/srvc-loadbalancer-mssql-sba-auth created

## Creadentials
# - 127.0.0.1,1433
# - sa
# - 'P@55w0rd!123'