version: "3.9"

services:
  ms-sql-b:
    image: ahsansoftengineer/ms-sql-b
    container_name: ms-sql-b
    build:
      context: ../__K8S/
      dockerfile: DockerfileSQL
    environment:
    - ACCEPT_EULA=Y
    - MSSQL_PID=Express
    - SA_PASSWORD=P@55w0rd!123
    volumes:
    - sql-vol-b:/var/opt/mssql
    ports:
    - "1432:1433"
    networks:
    - network-5201

  platformservice-b:
    build:
      context: .
      dockerfile: Dockerfile
    image: ahsansoftengineer/platformservice-b
    container_name: platformservice-b
    environment:
    - ASPNETCORE_URLS=http://+:5201
    - DOTNET_ENVIRONMENT=DockerCompose
    - ConnectionStrings__SbPlatform=Server=ms-sql-b,1433;Initial Catalog=PlatformDB;User ID=sa;Password=P@55w0rd!123;TrustServerCertificate=true;
    - CommandService=http://host.docker.internal:8201/api/c/platforms/
    ports:
    - "5201:5201"
    networks:
    - network-5201

networks:
  network-5201:
    driver: bridge

volumes:
  sql-vol-b:
    driver: local



## Docker Compose CLI
# docker-compose -f docker-compose.yaml up -d --build
# docker-compose down

## ROUTE (Docker Port Mapping)
# - http://localhost:5201/swagger/index.html
# - http://localhost:5201/api/platform
# - http://localhost:5201/api/platform/1

## InterService Comm (Docker Host IP Name)
# - http://host.docker.internal:8201/api/c/platforms/