################~~~~ Rabbit MQ SBA ~~~~~##################
#### Run Command
## BASH
# kubectl apply -f ./__K8S/A_DEPL_Broker/depl-rbmq-sba.yaml
# kubectl delete -f ./__K8S/A_DEPL_Broker/depl-rbmq-sba.yaml
# kubectl rollout restart deployments depl-rbmq-sba

#-----------------------------#
# (1) RabbitMQ Deployment (SBA)
# - kubectl get deployment
# - kubectl get deployment depl-rbmq-sba
# - kubectl delete deployment depl-rbmq-sba
#-----------------------------#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-rbmq-sba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbmq-sba
  template:
    metadata:
      labels:
        app: rbmq-sba
    spec:
      containers:
        - name: rbmq
          image: rabbitmq:3-management
          ports:
            - name: management
              containerPort: 15672
              protocol: TCP
            - name: amqp
              containerPort: 5672
              protocol: TCP
---
#---------------------------------------------#
# (2) RabbitMQ ClusterIP Service (for internal)
# - Production Required
# - kubectl get svc
# - kubectl get svc srvc-cip-rbmq-sba
#---------------------------------------------#

apiVersion: v1
kind: Service
metadata:
  name: srvc-cip-rbmq-sba
spec:
  type: ClusterIP
  selector:
    app: rbmq-sba
  ports:
    - name: management
      port: 15672
      targetPort: 15672
      protocol: TCP
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
---
#---------------------------------------------#
# (3) RabbitMQ LoadBalancer Service (external)
# - Production Required
# - kubectl get svc
# - kubectl get svc srvc-lb-rbmq-sba
# - http://localhost:15672/#/exchanges
#---------------------------------------------#
apiVersion: v1
kind: Service
metadata:
  name: srvc-lb-rbmq-sba
spec:
  type: LoadBalancer
  selector:
    app: rbmq-sba
  ports:
    - name: management
      port: 15672
      targetPort: 15672
      protocol: TCP
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
