apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-mssql
spec:
  resources:
    requests:
      storage: 500Mi
  accessModes:
  - ReadWriteMany

## Master Slave Arch
## Client Server
## 