################~~~~ SBA Auth ~~~~~##################
# - Deployment
# - ClusterIP
# - Node Port

## BASH BUILD Dockerfile
## -t tagname, -f file/reference, ./buildContext  
# docker build -t mansanhhub/sba-srvc-auth -f Projects/SBA.Auth/Dockerfile .
# docker push mansanhhub/sba-srvc-auth
# docker pull mansanhhub/sba-srvc-auth

#------------------------------------------------------------------------- 
## BASH RUN Deployment sba-srvc-auth
# kubectl apply -f ./__/K8S/B_DEPL_SRVC/sba-depl-auth.yaml
# kubectl get pods
# kubectl get deployments
# kubectl logs -l app=sba-srvc-auth --all-containers=true --tail=-1
# kubectl rollout restart deployments sba-depl-auth

## BASH DELETE (Deployments & Service)
# kubectl scale deployment sba-depl-auth --replicas=0
# kubectl delete -f ./__/K8S/B_DEPL_SRVC/sba-depl-auth.yaml
# kubectl delete deployments sba-depl-auth
# kubectl delete services sba-srvc-cip-auth
#------------------------------------------------------------------------- 
#### (1) API Deployment (Auth) 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sba-depl-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sba-srvc-auth
  template:
    metadata:
      labels:
        app: sba-srvc-auth
    spec:
      enableServiceLinks: false   # ✅ disables auto-injected env vars
      containers:
        - name: sba-srvc-auth
          image: mansanhhub/sba-srvc-auth
          imagePullPolicy: Always
          ports:
            - containerPort: 1104
          env:
            - name: DOTNET_ENVIRONMENT
              value: K8S
            - name: ASPNETCORE_URLS
              value: http://+:1104
              
            - name: ConnectionStrings__Redis
              value: "sba-srvc-cip-redis-dev:6379,password=P@55w0rd!123"
            - name: ConnectionStrings__SqlConnection
              value: "Server=sba-srvc-cip-mssql-dev.default.svc.cluster.local,1433;Initial Catalog=SBA_Auth;User ID=sa;Password=P@55w0rd!123;TrustServerCertificate=true;"
            
            - name: Clients__Http_Host__Gateway
              value: http://sba-srvc-cip-gateway:1100
            - name: Clients__Http_Host__Auth
              value: http://sba-srvc-cip-auth:1104


            - name: Clients__RabbitMQz__HostName
              value: sba-srvc-cip-rbmq.default.svc.cluster.local
            - name: Clients__RabbitMQz__Port
              value: "5672"
            - name: Clients__RabbitMQz__VirtualHost
              value: /
            - name: Clients__RabbitMQz__Username
              value: guest
            - name: Clients__RabbitMQz__Password
              value: guest
            # - name: Clients__RabbitMQz__Uri
            #   value: amqp://guest:guest@sba-srvc-cip-rbmq.default.svc.cluster.local/
---
#------------------------------------------------------------------------- 
#### (2) API Cluster IP (Auth)
# - We need ClusterIP for Inter Service Communication
# - Production Required
# kubectl port-forward svc/sba-srvc-cip-auth 1104:1104
# http://sba-srvc-cip-auth:1104/api/Auth/v1/swagger/index.html
# http://sba-srvc-cip-auth:1104/api/Auth/v1/_projectz-lookup/gets-lookup
---
apiVersion: v1
kind: Service
metadata:
  name: sba-srvc-cip-auth
spec:
  type: ClusterIP
  selector:
    app: sba-srvc-auth
  ports:
  - name: sba-srvc-auth
    protocol: TCP
    port: 1104
    targetPort: 1104
    # nodePort: Not a Valid Option for Cluster IP

---
#-------------------------------------------------------------------------
#### (3) API Node Port (Auth)
# - We need NodePort for External Service Access
# - No Production Required
apiVersion: v1
kind: Service
metadata:
  name: sba-srvc-np-auth
spec:
  type: NodePort
  selector:
    app: sba-srvc-auth
  ports:
    - name: sba-srvc-auth
      protocol: TCP
      port: 1104 # Node Port
      targetPort: 1104 # Pod's App port
      nodePort: 31104 # 30000-32767 (Host Port)

## ROUTES (K8S Node Port)
# - http://localhost:31104/api/Auth/v1/swagger/index.html
# - http://localhost:31104/api/Auth/v1/_projectz-lookup/gets-lookup