################~~~~ DB SBA Hierarchy ~~~~~##################
#### Run Command
## BASH
# kubectl apply -f ./__K8S/A_DEPL_SQL/depl-mssql-sba-all-dev.yaml
# kubectl delete -f ./__K8S/A_DEPL_SQL/depl-mssql-sba-all-dev.yaml

#### (3) DB Claim (Hierarchy) 

# - This Task Done Only Once
# - Creating Claim for Database
# kubectl get pvc
# kubectl get pvc claim-mssql-sba-all-dev
# kubectl delete pvc claim-mssql-sba-all-dev
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-mssql-sba-all-dev
spec:
  resources:
    requests:
      storage: 500Mi
  accessModes:
  - ReadWriteMany

---


#### (3) DB Deployment (Hierarchy) 
# - kubectl get deployment
# - kubectl get deployment depl-mssql-sba-all-dev
# - kubectl delete deployment depl-mssql-sba-all-dev
apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-mssql-sba-all-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-sba-all-dev
  template:
    metadata:
      labels:
        app: mssql-sba-all-dev
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          resources:
            limits:
              memory: 1Gi
              cpu: "1"
            requests:
              memory: 1Gi
              cpu: "1"
          env:
            - name: MSSQL_PID
              value: "Express"
            - name: ACCEPT_EULA
              value: "Y"
            # - name: SA_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: mssql
            #       key: SA_PASSWORD
            # The commented-out line should be removed if you're using the secret reference
            - name: SA_PASSWORD
              value: "P@55w0rd!123"
          volumeMounts:
            - mountPath: /var/opt/mssql/data
              name: mssqldb
      initContainers:
        - name: fix-perms
          image: busybox
          command: ["sh", "-c", "chown -R 10001:0 /var/opt/mssql"]
          volumeMounts:
            - name: mssqldb
              mountPath: /var/opt/mssql
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: claim-mssql-sba-all-dev

---
#------------------------------------------------------------------------- 
#### (4) DB ClusterIP (Hierarchy)
# - We need ClusterIP for Inter Service Communication
# - Production Required
# - kubectl get svc
# - kubectl get svc srvc-cip-mssql-sba-all-dev
apiVersion: v1
kind: Service
metadata:
  name: srvc-cip-mssql-sba-all-dev
spec:
  type: ClusterIP
  selector:
    app: mssql-sba-all-dev
  ports:
    - name: mssql
      protocol: TCP
      port: 1433 # Port -> Cluster 
      targetPort: 1433 # Port -> (Pod / Container)

---
#-------------------------------------------------------------------------
#### (6) DB LoadBalancer (Hierarchy)
# - We need LoadBalancer for External Service Access
# - No Production Required
# - kubectl get svc srvc-loadbalancer-mssql-sba-all-dev
## Creadentials for LoadBalancer
# - 127.0.0.1,1433 sa 'P@55w0rd!123'
apiVersion: v1
kind: Service
metadata:
  name: srvc-loadbalancer-mssql-sba-all-dev
spec:
  type: LoadBalancer
  selector:
    app: mssql-sba-all-dev
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433