apiVersion: v1
kind: Service
metadata:
  name: srvc-np-commands-d
spec:
  type: NodePort
  selector:
    app: commandservice-d
  ports:
    - name: commandservice-d
      protocol: TCP
      port: 8401
      targetPort: 8401
      nodePort: 30841
---
apiVersion: v1
kind: Service
metadata:
  name: srvc-np-platforms-d
spec:
  type: NodePort
  selector:
    app: platformservice-d
  ports:
    - name: platformservice-d
      protocol: TCP
      port: 5401 # Cluster Port
      targetPort: 5401 # Pod's App port
      nodePort: 30541 # Host Access (Windows) Range 30000-32767

## BASH K8S SERVICE NODE PORT
# kubectl apply -f 2_srvc-np.yaml
# kubectl get services
# kubectl get nodes -o wide # EXTERNAL-IP replace with localhost
# kubectl delete -f 2_srvc-np.yaml

## ROUTES (K8S Node Port)
# - http://localhost:30841/swagger/index.html
# - http://localhost:30841/api/c/platforms POST

## Inter Service Comm (Cluster IP)
# - srvc-clusterip:8401/api/c/platforms/


# ### ROUTES (K8S Node Port)
# - http://localhost:30541/swagger/index.html
# - http://localhost:30541/api/platform
# - http://localhost:30541/api/platform/1