version: "3.9"

services:
  srvc-sba-auth:
    build:
      context: .
      dockerfile: Dockerfile
    image: mansanhhub/srvc-sba-auth
    container_name: srvc-sba-auth
    environment:
      - ASPNETCORE_URLS=http://+:5802
      - DOTNET_ENVIRONMENT=DockerCompose
    ports:
      - "5802:5802" # Map host port 5802 to container port 5802

# ### Docker Compose CLI
# docker-compose up -d --build
# docker-compose down

# ### ROUTE (Docker Port Mapping)
# - http://localhost:5806/api/auth/v1/swagger/index.html
# - http://localhost:5806/api/auth/v1/_projectz-lookup/gets-lookup
