apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-mssql
spec:
  resources:
    requests:
      storage: 500Mi
  accessModes:
  - ReadWriteMany

## Master Slave Arch
## Client Server
### Create Claims
# - This Task Done Only Once
# - Creating Claim for Database

# kubectl apply -f _0_pvc-local.yaml
# kubectl get pvc
# kubectl delete -f _0_pvc-local.yaml