version: "3.9"

services:
  srvc-sba-hierarchy:
    build:
      context: .
      dockerfile: Dockerfile
    image: mansanhhub/srvc-sba-hierarchy
    container_name: srvc-sba-hierarchy
    environment:
      - ASPNETCORE_URLS=http://+:5806
      - DOTNET_ENVIRONMENT=DockerCompose
    ports:
      - "5806:5806" # Map host port 5806 to container port 5806

# ### Docker Compose CLI
# docker-compose up -d --build
# docker-compose down

# ### ROUTE (Docker Port Mapping)
# - http://localhost:5806/api/hierarchy/v1/swagger/index.html
# - http://localhost:5806/api/hierarchy/v1/_projectz-lookup/gets-lookup
