apiVersion: v1
kind: Service
metadata:
  name: srvc-np-platforms-d
spec:
  type: NodePort
  selector:
    app: platformservice-d
  ports:
    - name: platformservice-d
      protocol: TCP
      port: 5401 # Cluster Port
      targetPort: 5401 # Pod's App port
      nodePort: 30541 # Host Access (Windows) Range 30000-32767

#### BASH K8S SERVICE NODE PORT
# - We need Node Port to Access application via Host
# kubectl apply -f 2_srvc-np-platforms.yaml
# kubectl get pods
# kubectl get deployments
# kubectl delete -f 2_srvc-np-platforms.yaml

# ### ROUTES (K8S Node Port)
# - http://localhost:30541/swagger/index.html
# - http://localhost:30541/api/platform
# - http://localhost:30541/api/platform/1